name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4

  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDest-Voxels-Vanilla-${{ env.SUFFIX }}.pk3" . -i filter/* CHANGELOG.md LICENSE LICENSE.VoxelDoom README.md

  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDest-Voxels-Peppergrinder-${{ env.SUFFIX }}.pk3" . -i models/Peppergrinder/* CHANGELOG.md LICENSE LICENSE.VoxelDoom MODELDEF.peppergrinder README.md

  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDest-Voxels-Radtech-${{ env.SUFFIX }}.pk3" . -i voxels/Radtech/* CHANGELOG.md LICENSE LICENSE.VoxelDoom VOXELDEF.radtech README.md

  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDest-Voxels-full-${{ env.SUFFIX }}.pk3" . -i filter/* models/* voxels/* CHANGELOG.md LICENSE LICENSE.VoxelDoom MODELDEF.* README.md VOXELDEF.*
