name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "HDest-Voxels-${{ env.SUFFIX }}.pk3" . -i filter/* models/* CHANGELOG.md LICENSE LICENSE.VoxelDoom MODELDEF.* README.md
